# Generated by Django 3.0.1 on 2020-07-04 15:59

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name', max_length=100)),
                ('last_name', models.CharField(help_text='Last name', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email ID', max_length=254)),
                ('contact_number', phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31)),
            ],
        ),
    ]
